export const SELECTED_STOCK = 'app/TradingManager/SELECTED_STOCK'
export const SELECTED_TYPE = 'app/TradingManager/SELECTED_TYPE'
export const SELECTED_STRATEGY = 'app/TradingManager/SELECTED_STRATEGY'
export const STARTED_TRADING = 'app/TradingManager/STARTED_TRADING'
export const FINALIZED_TRADING = 'app/TradingManager/FINALIZEED_TRADING'
export const MOVED_STOP_LOSS = 'app/TradingManager/MOVED_STOP_LOSS'
export const REACHED_TAKE_PROFIT = 'app/TradingManager/REACHED_TAKE_PROFIT'
export const REACHED_STOP_LOSS = 'app/TradingManager/REACHED_STOP_LOSS'
